version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_inventory_container
    ports:
      - "5000:5000"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - ADMIN_PASSOWRD=${ADMIN_PASSWORD}
      - SURAJ_PASSOWRD=${SURAJ_PASSWORD}
      - DB_PATH=${DB_PATH}
    volumes:
      - ./data:/app/data
    restart: always
