version: '3.8'

services:
  inventory-app:
    build: .
    container_name: flask_inventory_container
    ports:
      - "5000:5000"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - DB_PATH=/app/data/database.db
    volumes:
      - ./data:/app/data
    restart: always
